version: '3'

services:
  jenkins-use-docker:
    image: qyvlik/jenkins-use-docker:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_PATH}:/usr/bin/docker
      - ${LIBLTDL_PATH}:/usr/lib/x86_64-linux-gnu/libltdl.so.7
      # for docker login
      - ~/.docker/:/root/.docker
      - ${JENKINS_VOLUMES}:/var/jenkins_home
    ports:
      - "9090:8080"
      - "50000:50000"
